steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'demo-5-gcp-cloud-sql'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svccloudsql:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svccloudsql:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'svc-cloudsql'
    - '--image'
    - 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svccloudsql:$COMMIT_SHA'
    - '--region'
    - 'us-east1'
    - '--platform'
    - 'managed'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '1'
    - '--allow-unauthenticated'
    - '--service-account'
    - 'sa-svc-cloudsql@$PROJECT_ID.iam.gserviceaccount.com'
    - '--add-cloudsql-instances'
    - '$PROJECT_ID:us-central1:my-awesome-db-instance'

images:
- 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svccloudsql'